package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * Evenement generated by hbm2java
 */
@Entity
@Table(name="evenement"
    ,schema="public"
)
public class Evenement  implements java.io.Serializable {


     private int idEvent;
     private String nom;
     private String type;
     private int prix;
     private Date date;
     private boolean validation;
     private String inscription;

    public Evenement() {
    }

	
    public Evenement(int idEvent) {
        this.idEvent = idEvent;
    }
    public Evenement(int idEvent,String nom, String type, int prix, Date date,String inscription) {
       this.idEvent = idEvent;
       this.type = type;
       this.prix = prix;
       this.date = date;
       this.nom=nom;
       this.inscription=inscription;
    }
   
     @Id 

    
    @Column(name="idEvent", unique=true, nullable=false)
    public int getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(int idEvent) {
        this.idEvent = idEvent;
    }
@Column(name="nom", length=258)
    
    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="type", length=258)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
 
    @Column(name="prix")
    public int getPrix() {
        return this.prix;
    }
    
    public void setPrix(int prix) {
        this.prix = prix;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=258)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

  @Column(name="validation")
    public boolean isValidation() {
        return validation;
    }

    public void setValidation(boolean validation) {
        this.validation = validation;
    }

    

    public String getInscription() {
        return inscription;
    }

    public void setInscription(String inscription) {
        this.inscription = inscription;
    }
   
}


