package model;
// Generated 2 mai 2015 11:01:58 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Feeds generated by hbm2java
 */
@Entity
@Table(name = "feeds", schema = "public")
public class Feeds  implements java.io.Serializable {


     @Id
     private int id;
     @Temporal(javax.persistence.TemporalType.DATE)
     private Date timestamp;
     private String name;
     private String image;
     private String status;
     private String profilepic;
     private String url;

    public Feeds() {
    }

	
    public Feeds(int id) {
        this.id = id;
    }
    public Feeds(int id, String name, String image, String status, String profilepic, String url) {
       this.id = id;
       this.name = name;
       this.image = image;
       this.status = status;
       this.profilepic = profilepic;
       this.url = url;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getProfilepic() {
        return this.profilepic;
    }
    
    public void setProfilepic(String profilepic) {
        this.profilepic = profilepic;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


