package model;
// Generated 26 mars 2014 16:28:09 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Garde generated by hbm2java
 */
@Entity
@Table(name="garde"
    ,schema="public"
)
public class Garde  implements java.io.Serializable {


     private int id;
     private Date debut;
     private Date fin;

    public Garde() {
    }

	
    public Garde(int id) {
        this.id = id;
    }
    public Garde(int id, Date debut, Date fin) {
       this.id = id;
       this.debut = debut;
       this.fin = fin;
    }
   
     @Id @GeneratedValue

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="debut", length=13)
    public Date getDebut() {
        return this.debut;
    }
    
    public void setDebut(Date debut) {
        this.debut = debut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fin", length=13)
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


