package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", schema = "public"
)
public class Hotel implements java.io.Serializable {

    private int idHotel;
    private String nomH;
    private String sitewebH;
    private Double longitude;
    private Double latitude;
    private String description;
    private int nbreetoile;
    private String telephoneH;
    private String emailH;
    private String image;
    private boolean validation;
    private boolean archive;
    private Ville idVille;
    private String imagemobile;

    private String status, profilePic, timeStamp, url;

    public String getImagemobile() {
        return imagemobile;
    }

    public void setImagemobile(String imagemobile) {
        this.imagemobile = imagemobile;
    }
    // private Set<ClientMobile> clientsMobiles ;
    //private Pay idPays;

    public Hotel() {
    }

    public Ville getIdVille() {
        return idVille;
    }

    public void setIdVille(Ville idVille) {
        this.idVille = idVille;
    }

    public Hotel(int idHotel, int nbreetoile) {
        this.idHotel = idHotel;
        this.nbreetoile = nbreetoile;
    }

    public Hotel(int idHotel, String image, Ville ville, String nomH, String sitewebH, Double longitude, Double latitude, String description, int nbreetoile, String telephoneH, String emailH) {
        this.idHotel = idHotel;
        this.image = image;
        this.nomH = nomH;
        this.idVille = ville;
        this.sitewebH = sitewebH;
        this.longitude = longitude;
        this.latitude = latitude;
        this.description = description;
        this.nbreetoile = nbreetoile;
        this.telephoneH = telephoneH;
        this.emailH = emailH;
    }

    @Id

    @Column(name = "idHotel", unique = true, nullable = false)
    public int getIdHotel() {
        return this.idHotel;
    }

    public void setIdHotel(int idHotel) {
        this.idHotel = idHotel;
    }

    @Column(name = "nomH", length = 258)
    public String getNomH() {
        return this.nomH;
    }

    public void setNomH(String nomH) {
        this.nomH = nomH;
    }

    @Column(name = "sitewebH", length = 258)
    public String getSitewebH() {
        return this.sitewebH;
    }

    public void setSitewebH(String sitewebH) {
        this.sitewebH = sitewebH;
    }

    @Column(name = "longitude", precision = 20, scale = 20)
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @Column(name = "latitude", precision = 20, scale = 20)
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "description", length = 10000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "nbreetoile", nullable = false)
    public int getNbreetoile() {
        return this.nbreetoile;
    }

    public void setNbreetoile(int nbreetoile) {
        this.nbreetoile = nbreetoile;
    }

    @Column(name = "telephoneH", length = 258)
    public String getTelephoneH() {
        return this.telephoneH;
    }

    public void setTelephoneH(String telephoneH) {
        this.telephoneH = telephoneH;
    }

    @Column(name = "emailH", length = 258)
    public String getEmailH() {
        return this.emailH;
    }

    public void setEmailH(String emailH) {
        this.emailH = emailH;
    }

    @Column(name = "image", length = 258)
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "validation")
    public boolean isValidation() {
        return validation;
    }

    public void setValidation(boolean validation) {
        this.validation = validation;
    }

    @Column(name = "archive")
    public boolean isArchive() {
        return archive;
    }

    public void setArchive(boolean archive) {
        this.archive = archive;
    }

    @Column(name = "status", length = 258)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "profilepic", length = 258)
    public String getProfilePic() {
        return profilePic;
    }

    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    @Column(name = "url", length = 258)
    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Column(name = "url", length = 258)
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    
}
