package model;
// Generated Mar 29, 2014 12:56:35 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,schema="public"
)
public class Hotel  implements java.io.Serializable {


     private int idHotel;
     private String nomH;
     private String categorieH;
     private String sitewebH;
     private Double longitude;
     private Double latitude;
     private String description;
     private int nbreetoile;
     private String telephoneH;
     private String emailH;

    public Hotel() {
    }

	
    public Hotel(int idHotel, int nbreetoile) {
        this.idHotel = idHotel;
        this.nbreetoile = nbreetoile;
    }
    public Hotel(int idHotel, String nomH, String categorieH, String sitewebH, Double longitude, Double latitude, String description, int nbreetoile, String telephoneH, String emailH) {
       this.idHotel = idHotel;
       this.nomH = nomH;
       this.categorieH = categorieH;
       this.sitewebH = sitewebH;
       this.longitude = longitude;
       this.latitude = latitude;
       this.description = description;
       this.nbreetoile = nbreetoile;
       this.telephoneH = telephoneH;
       this.emailH = emailH;
    }
   
     @Id @GeneratedValue

    
    @Column(name="id_hotel", unique=true, nullable=false)
    public int getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(int idHotel) {
        this.idHotel = idHotel;
    }

    
    @Column(name="nom_h", length=254)
    public String getNomH() {
        return this.nomH;
    }
    
    public void setNomH(String nomH) {
        this.nomH = nomH;
    }

    
    @Column(name="categorie_h", length=254)
    public String getCategorieH() {
        return this.categorieH;
    }
    
    public void setCategorieH(String categorieH) {
        this.categorieH = categorieH;
    }

    
    @Column(name="siteweb_h", length=254)
    public String getSitewebH() {
        return this.sitewebH;
    }
    
    public void setSitewebH(String sitewebH) {
        this.sitewebH = sitewebH;
    }

    
    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="description", length=254)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="nbreetoile", nullable=false)
    public int getNbreetoile() {
        return this.nbreetoile;
    }
    
    public void setNbreetoile(int nbreetoile) {
        this.nbreetoile = nbreetoile;
    }

    
    @Column(name="telephone_h", length=254)
    public String getTelephoneH() {
        return this.telephoneH;
    }
    
    public void setTelephoneH(String telephoneH) {
        this.telephoneH = telephoneH;
    }

    
    @Column(name="email_h", length=254)
    public String getEmailH() {
        return this.emailH;
    }
    
    public void setEmailH(String emailH) {
        this.emailH = emailH;
    }




}


