package model;
// Generated 26 mars 2014 16:28:09 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="image"
    ,schema="public"
)
public class Image  implements java.io.Serializable {


@Id
     @Column(name="id", unique=true, nullable=false)
     private int id;
@Column(name="nom", length=25)
     private String nom;
@Column(name="description", length=25)
     private String description;
@Column(name="data")
     @Lob
     private byte[] data;

    public Image() {
    }

	
    public Image(int id) {
        this.id = id;
    }
    public Image(int id, String nom, String description, byte[] data) {
       this.id = id;
       this.nom = nom;
       this.description = description;
       this.data = data;
    }
   
         public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
        public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
        public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
        public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }




}


