package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="image"
    ,schema="public"
)
public class Image  implements java.io.Serializable {


     private int idImage;
     private String nom;
     private String description;
     private String data;
    

    public Image() {
    }

	
    public Image(int idImage) {
        this.idImage = idImage;
    }
    public Image(int idImage, String nom, String description) {
       this.idImage = idImage;
       this.nom = nom;
       this.description = description;
      
    }
   
     @Id 

    
    @Column(name="idImage", unique=true, nullable=false)
    public int getIdImage() {
        return this.idImage;
    }
    
    public void setIdImage(int idImage) {
        this.idImage = idImage;
    }

    
    @Column(name="nom", length=258)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="description", length=10000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    
    }


