package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="image"
    ,schema="public"
)
public class Image  implements java.io.Serializable {


     private int id;
     private String nom;
     private String description;
     private byte[] data;

    public Image() {
    }

	
    public Image(int id) {
        this.id = id;
    }
    public Image(int id, String nom, String description, byte[] data) {
       this.id = id;
       this.nom = nom;
       this.description = description;
       this.data = data;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nom", length=25)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="description", length=25)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="data")
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }




}


