package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Monument generated by hbm2java
 */
@Entity
@Table(name="monument"
    ,schema="public"
)
public class Monument  implements java.io.Serializable {


     private int idMonument;
     private String nomM;
     private String categorieM;
     private String sitewebM;
     private Double longitude;
     private Double latitude;
     private String description;
     private String type;
     private Date dateconstruction;
     private Date finconstruction;
     private String historique;

    public Monument() {
    }

	
    public Monument(int idMonument) {
        this.idMonument = idMonument;
    }
    public Monument(int idMonument, String nomM, String categorieM, String sitewebM, Double longitude, Double latitude, String description, String type, Date dateconstruction, Date finconstruction, String historique) {
       this.idMonument = idMonument;
       this.nomM = nomM;
       this.categorieM = categorieM;
       this.sitewebM = sitewebM;
       this.longitude = longitude;
       this.latitude = latitude;
       this.description = description;
       this.type = type;
       this.dateconstruction = dateconstruction;
       this.finconstruction = finconstruction;
       this.historique = historique;
    }
   
     @Id 

    
    @Column(name="id_monument", unique=true, nullable=false)
    public int getIdMonument() {
        return this.idMonument;
    }
    
    public void setIdMonument(int idMonument) {
        this.idMonument = idMonument;
    }

    
    @Column(name="nom_m", length=254)
    public String getNomM() {
        return this.nomM;
    }
    
    public void setNomM(String nomM) {
        this.nomM = nomM;
    }

    
    @Column(name="categorie_m", length=254)
    public String getCategorieM() {
        return this.categorieM;
    }
    
    public void setCategorieM(String categorieM) {
        this.categorieM = categorieM;
    }

    
    @Column(name="siteweb_m", length=254)
    public String getSitewebM() {
        return this.sitewebM;
    }
    
    public void setSitewebM(String sitewebM) {
        this.sitewebM = sitewebM;
    }

    
    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="description", length=254)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="type", length=254)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateconstruction", length=13)
    public Date getDateconstruction() {
        return this.dateconstruction;
    }
    
    public void setDateconstruction(Date dateconstruction) {
        this.dateconstruction = dateconstruction;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="finconstruction", length=13)
    public Date getFinconstruction() {
        return this.finconstruction;
    }
    
    public void setFinconstruction(Date finconstruction) {
        this.finconstruction = finconstruction;
    }

    
    @Column(name="historique", length=258)
    public String getHistorique() {
        return this.historique;
    }
    
    public void setHistorique(String historique) {
        this.historique = historique;
    }




}


