package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name = "pay", schema = "public"
)
public class Pay implements java.io.Serializable {

    private int idPay;
    private String nom;
    private Set<Ville> ville; 

    public Pay() {
    }

    public Pay(int idPay) {
        this.idPay = idPay;
    }

    public Pay(int idPay, String nom) {
        this.idPay= idPay;
        this.nom = nom;
       
    }

    @Id

    @Column(name = "idPay", unique = true, nullable = false)
    public int getIdPay() {
        return this.idPay;
    }

    public void setIdPay(int idPay) {
        this.idPay = idPay;
    }

    @Column(name = "nom", length = 258)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

   

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 31 * hash + this.idPay;
        hash = 31 * hash + (this.nom != null ? this.nom.hashCode() : 0);
       // hash = 31 * hash + (this.image != null ? this.image.hashCode() : 0);
     //   hash = 31 * hash + (this.ville != null ? this.ville.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pay other = (Pay) obj;
        if (this.idPay != other.idPay) {
            return false;
        }
        if ((this.nom == null) ? (other.nom != null) : !this.nom.equals(other.nom)) {
            return false;
        }
//        if ((this.image == null) ? (other.image != null) : !this.image.equals(other.image)) {
//            return false;
//        }
      //  if (this.ville != other.ville && (this.ville == null || !this.ville.equals(other.ville))) {
       //     return false;
      //  }
        return true;
    }

     @OneToMany(mappedBy = "pay")  
    public Set<Ville> getVille() {
        return ville;
    }

    public void setVille(Set<Ville> ville) {
        this.ville = ville;
    }

}
