package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pharmacie generated by hbm2java
 */
@Entity
@Table(name="pharmacie"
    ,schema="public"
)
public class Pharmacie  implements java.io.Serializable {


     private int idPhar;
     private String telephone;
     private String image;
     private String email;
     private String siteweb;
     private Double longitude;
     private Double latitude;
     private String type;
     private String nom;
     private String description;
     private boolean archive;
     private boolean validation;
     private Ville idVille;
 private String imagemobile;

    public String getImagemobile() {
        return imagemobile;
    }

    public void setImagemobile(String imagemobile) {
        this.imagemobile = imagemobile;
    }
    public Pharmacie() {
    }

	
    public Pharmacie(int idPhar) {
        this.idPhar = idPhar;
    }
    public Pharmacie(int idPhar,String image,Ville ville, String telephone, String email, String siteweb, Double longitude, Double latitude, String type, String nom, String description) {
       this.idPhar = idPhar;
       this.image=image;
       this.telephone = telephone;
       this.email = email;
       this.siteweb = siteweb;
       this.longitude = longitude;
       this.latitude = latitude;
       this.type = type;
       this.nom = nom;
        this.idVille=ville;
       this.description = description;
    }
   public Ville getIdVille() {
        return idVille;
    }

    public void setIdVille(Ville ville) {
        this.idVille = ville;
    }
    
     @Id 
    @Column(name="idPhar", unique=true, nullable=false)
    public int getIdPhar() {
        return this.idPhar;
    }
    
    public void setIdPhar(int idPhar) {
        this.idPhar = idPhar;
    }

    
    @Column(name="telephone", length=258)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="email", length=258)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="siteweb", length=258)
    public String getSiteweb() {
        return this.siteweb;
    }
    
    public void setSiteweb(String siteweb) {
        this.siteweb = siteweb;
    }

    
    @Column(name="longitude")
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="latitude")
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="type", length=258)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="nom", length=258)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="description", length=10000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    
  @Column(name="image", length=258)
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }


  @Column(name="validation")
    public boolean isValidation() {
        return validation;
    }

    public void setValidation(boolean validation) {
        this.validation = validation;
    }

    @Column(name="archive")
    public boolean isArchive() {
        return archive;
    }

    public void setArchive(boolean archive) {
        this.archive = archive;
    }

@Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + (this.nom != null ? this.nom.hashCode() : 0);
        hash = 17 * hash + (this.longitude != null ? this.longitude.hashCode() : 0);
        hash = 17 * hash + (this.latitude != null ? this.latitude.hashCode() : 0);
         hash = 17 * hash + (this.telephone != null ? this.telephone.hashCode() : 0);
        hash = 17 * hash + (this.type != null ? this.type.hashCode() : 0);
        
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pharmacie other = (Pharmacie) obj;
        if ((this.nom == null) ? (other.nom != null) : !this.nom.equals(other.nom)) {
            return false;
        }
        if (this.longitude != other.longitude && (this.longitude == null || !this.longitude.equals(other.longitude))) {
            return false;
        }
        if (this.latitude != other.latitude && (this.latitude == null || !this.latitude.equals(other.latitude))) {
            return false;
        }
          if (this.telephone != other.telephone && (this.telephone == null || !this.telephone.equals(other.telephone))) {
            return false;
        }
           if (this.type != other.type && (this.type == null || !this.type.equals(other.type))) {
            return false;
        }
        return true;
    }
}

