package model;
// Generated Apr 2, 2014 11:37:33 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville", schema = "public"
)
public class Ville implements java.io.Serializable {

    private int idVille;
    private String gouvernorat;
    private String nom;
    private String rue;
    private Pay pay;

    public Ville() {
    }

    public Ville(int idVille) {
        this.idVille = idVille;
    }

    public Ville(int idVille,String gouvernorat, String nom, String rue) {
        this.idVille = idVille;
        this.gouvernorat = gouvernorat;
        this.nom = nom;
        this.rue = rue;
    }

    @Id
    @Column(name = "idVille", unique = true, nullable = false)
    public int getIdVille() {
        return this.idVille;
    }

    public void setIdVille(int idVille) {
        this.idVille = idVille;
    }

    @Column(name = "gouvernorat", length = 258)
    public String getGouvernorat() {
        return this.gouvernorat;
    }

    public void setGouvernorat(String gouvernorat) {
        this.gouvernorat = gouvernorat;
    }

    @Column(name = "nom", length = 258)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "rue", length = 258)
    public String getRue() {
        return this.rue;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    
    public Pay getPay() {
        return pay;
    }

    public void setPay(Pay pay) {
        this.pay = pay;
    } 

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + this.idVille;
       // hash = 23 * hash + (this.gouvernorat != null ? this.gouvernorat.hashCode() : 0);
        hash = 23 * hash + (this.nom != null ? this.nom.hashCode() : 0);
      //  hash = 23 * hash + (this.rue != null ? this.rue.hashCode() : 0);
            //  hash = 23 * hash + (this.pay != null ? this.pay.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ville other = (Ville) obj;
        if (this.idVille != other.idVille) {
            return false;
        }
//        if ((this.gouvernorat == null) ? (other.gouvernorat != null) : !this.gouvernorat.equals(other.gouvernorat)) {
//            return false;
//        }
        if ((this.nom == null) ? (other.nom != null) : !this.nom.equals(other.nom)) {
            return false;
        }
        if ((this.rue == null) ? (other.rue != null) : !this.rue.equals(other.rue)) {
            return false;
        }
        
     /*   if (this.pay != other.pay && (this.pay == null || !this.pay.equals(other.pay))) {
            return false;
        }*/
        return true;
    }

    
    
}
